"""followers

Revision ID: d9d083a0a654
Revises: 1e6370fa19ae
Create Date: 2019-10-26 13:56:27.754880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d9d083a0a654"
down_revision = "1e6370fa19ae"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "followers",
        sa.Column("follower_id", sa.Integer(), nullable=True),
        sa.Column("followed_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["followed_id"], ["user.id"]),
        sa.ForeignKeyConstraint(["follower_id"], ["user.id"]),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("followers")
    # ### end Alembic commands ###
